# =============================================================================
# ZenNode Cloud — Pydantic Schemas (API request/response models)
# =============================================================================

from datetime import date
from typing import Optional
from pydantic import BaseModel, EmailStr, Field


# ── Auth ──────────────────────────────────────────────────────────────────────

class SignupRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8)
    anonymous_id: str = Field(description="Local UUID generated by the VS Code extension")
    display_name: Optional[str] = None


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user_id: str
    anonymous_id: str
    team_id: Optional[str] = None
    role: str


class MeResponse(BaseModel):
    user_id: str
    email: str
    anonymous_id: str
    display_name: Optional[str]
    role: str
    team_id: Optional[str]
    show_name_to_team: bool


# ── Teams ─────────────────────────────────────────────────────────────────────

class CreateTeamRequest(BaseModel):
    name: str = Field(min_length=2, max_length=80)


class JoinTeamRequest(BaseModel):
    invite_code: str


class TeamResponse(BaseModel):
    team_id: str
    name: str
    invite_code: str
    member_count: int


class TeamMember(BaseModel):
    anonymous_id: str
    display_name: Optional[str]      # null unless show_name_to_team=True
    role: str
    avg_score_today: Optional[float]
    current_state: Optional[str]


class TeamMembersResponse(BaseModel):
    team_id: str
    team_name: str
    members: list[TeamMember]


# ── Sync ──────────────────────────────────────────────────────────────────────

class SyncSessionRequest(BaseModel):
    """
    Anonymized session summary sent from local backend → cloud.
    Contains NO raw behavioral data, NO keystroke counts, NO code content.
    """
    anonymous_user_id: str
    session_id: str
    session_date: date
    avg_score: float = Field(ge=0, le=100)
    max_score: float = Field(ge=0, le=100)
    overload_count: int = Field(ge=0)
    flow_seconds: float = Field(ge=0)
    friction_seconds: float = Field(ge=0)
    fatigue_seconds: float = Field(ge=0)
    overload_seconds: float = Field(ge=0)
    snapshot_count: int = Field(ge=0)


class SyncResponse(BaseModel):
    accepted: int
    message: str


# ── LLM Intervention ──────────────────────────────────────────────────────────

class InterventionRequest(BaseModel):
    score: float = Field(ge=0, le=100)
    state: str
    switch_rate: float = Field(ge=0, le=100)
    error_rate: float  = Field(ge=0, le=100)
    undo_rate: float   = Field(ge=0, le=100)
    idle_ratio: float  = Field(ge=0, le=100)
    paste_ratio: float = Field(ge=0, le=100)
    keystrokes: int    = Field(ge=0)
    backspaces: int    = Field(ge=0)
    tab_switches: int  = Field(ge=0)
    undos: int         = Field(ge=0)
    idle_seconds: float    = Field(ge=0)
    duration_seconds: float = Field(ge=0)
    pasted_chars: int  = Field(ge=0)
    total_chars: int   = Field(ge=0)


class InterventionResponse(BaseModel):
    intervention: Optional[str]


# ── Dashboard ─────────────────────────────────────────────────────────────────

class TeamDashboardResponse(BaseModel):
    team_id: str
    team_name: str
    member_count: int
    avg_team_score_today: float
    avg_team_score_week: float
    total_overloads_today: int
    total_overloads_week: int
    state_distribution_today: dict[str, float]   # state → total seconds
    burnout_risk_members: int                      # members with avg > 70 today


class DailyTrend(BaseModel):
    date: str
    avg_score: float
    overload_count: int
    member_count: int


class TeamTrendResponse(BaseModel):
    team_id: str
    days: list[DailyTrend]
